title: Alec's Portfolio
email: aswyen@gmail.com
description: >- # Your site description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aswyen.github.io" # your GitHub Pages URL
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-livereload
collections:
  projects:
    output: true
header_pages:
  - index.html
  - resume.md
  - projects.html
  - blog.html
  - contact.html
